#
# runtime base
# 
#=============================================================================

ARG IMAGE_PREFIX
ARG VERSION

FROM ${IMAGE_PREFIX}run:${VERSION}

ARG STAGE

ARG DUSER_UID

#--

USER 0

ADD docker/${STAGE} /docker.${STAGE}/
RUN /docker.${STAGE}/build.sh

USER ${DUSER_UID}
